image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy
  - clean

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "cd source"
    - "rmdir /Q /S obj"
    - "rmdir /Q /S bin"
    - "cd .."
    - "dotnet build source"

test:
  stage: test
  script:
    - "dotnet test tests"

deploy:
  stage: deploy
  script:
    - "dotnet publish source -c release /p:PublishTrimmed=true /p:PublishReadyToRun=true"
    - "dotnet publish source -c release -r linux-x64"
    - 7z a -tzip package.zip @includefiles.txt
  artifacts: 
    paths:
      - package.zip

clean:
  stage: clean
  script:
    - "cd source"
    - "rmdir /Q /S obj"
    - "rmdir /Q /S bin"
    - "cd .."
