image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

before_script:
  - "dotnet clean"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build source"

test:
  stage: test
  script:
    - "dotnet test tests"

deploy:
  stage: deploy
  script:
    - "dotnet publish source -c release /p:PublishReadyToRun=true"
    - "dotnet publish source -c release -r linux-x64"
    - "dotnet publish source -c release -r osx-x64"
    - Copy-Item "source\bin\release\netcoreapp3.1\win-x64\publish\source.exe" -Destination "assembler.exe" -Force
    - Copy-Item "source\bin\release\netcoreapp3.1\linux-x64\publish\source" -Destination "assembler_linux" -Force
    - Copy-Item "source\bin\release\netcoreapp3.1\osx-x64\publish\source" -Destination "assembler_mac" -Force
    - Copy-Item "source\obj\release\netcoreapp3.1\win-x64\source.dll" -Destination "assembler.dll" -Force
  artifacts: 
    paths:
      - assembler.exe
      - assembler_linux
      - assembler_mac
      - assembler.dll
      - BatchFiles.md
      - License.md
      - README.md
      - assets/
      - examples/
    expire_in: 2 weeks