image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

before_script:
  - "dotnet clean"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build source"

test:
  stage: test
  script:
    - "dotnet test tests"

deploy:
  stage: deploy
  script:
    - "dotnet publish source -c release /p:PublishTrimmed=true /p:PublishReadyToRun=true"
    - "dotnet publish source -c release -r linux-x64"
  artifacts: 
    paths:
      - source\bin\release\netcoreapp3.1\win-x64\publish\source.exe
      - source\bin\release\netcoreapp3.1\linux-x64\publish\source
      - source\obj\release\netcoreapp3.1\win-x64\source.dll
      - articles\BatchFiles.md
      - License.md
      - index.md
      - assets/
      - examples/
    expire_in: 2 weeks