name: deploy

on:
  workflow_call:

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Pandoc
      uses: docker://pandoc/latex:2.9
      with:
        args: -o stitch-manual.pdf BatchFiles.md
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: manual
       path: stitch-manual.pdf
       retention-days: 21

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Deploy
      run: |
       dotnet publish stitch -c release -r win-x64 --self-contained
       dotnet publish stitch -c release -r win-arm64 --self-contained
       Copy-Item "stitch\bin\release\net7.0\win-x64\publish\stitch.exe" -Destination "stitch.exe" -Force
       Copy-Item "stitch\bin\release\net7.0\win-arm64\publish\stitch.exe" -Destination "stitch_arm.exe" -Force
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: nightly-deploy-windows
       path: |
        stitch.exe
        stitch_arm.exe
        License.md
        README.md
        alphabets/
        assets/
        images/
        batchfiles/
        datasets/
        templates/
       retention-days: 21

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Deploy
      run: |
       dotnet publish stitch -c release -r linux-x64 --self-contained
       dotnet publish stitch -c release -r linux-arm64 --self-contained
       cp "stitch/bin/release/net7.0/linux-x64/publish/stitch" stitch.bin -f
       cp "stitch/bin/release/net7.0/linux-arm64/publish/stitch" stitch_arm -f
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: nightly-deploy-linux
       path: |
        stitch.bin
        stitch_arm
        License.md
        README.md
        alphabets/
        assets/
        images/
        batchfiles/
        datasets/
        templates/
       retention-days: 21

  osx:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Deploy
      run: |
       dotnet publish stitch -c release -r osx-x64 --self-contained
       dotnet publish stitch -c release -r osx.11.0-arm64 --self-contained
       cp "stitch/bin/release/net7.0/osx-x64/publish/stitch" stitch.bin
       cp "stitch/bin/release/net7.0/osx.11.0-arm64/publish/stitch" stitch_arm
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: nightly-deploy-osx
       path: |
        stitch.bin
        stitch_arm
        License.md
        README.md
        alphabets/
        assets/
        images/
        batchfiles/
        datasets/
        templates/
       retention-days: 21
