name: deploy

on:
  workflow_call:

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Use Pandoc
      uses: docker://pandoc/latex:2.9
      with:
        args: -o manual.pdf BatchFiles.md
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: manual
       path: manual.pdf
       retention-days: 21

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Deploy
      run: |
       dotnet publish source -c release /p:PublishReadyToRun=true
       dotnet publish source -c release -r win-arm64
       Copy-Item "source\bin\release\net6.0\win-x64\publish\source.exe" -Destination "assembler.exe" -Force
       Copy-Item "source\bin\release\net6.0\win-arm64\publish\source.exe" -Destination "assembler_arm.exe" -Force
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: nightly-deploy-windows
       path: |
        assembler.exe
        assembler_arm.exe
        License.md
        README.md
        alphabets/
        assets/
        batchfiles/
        datasets/
        templates/
       retention-days: 21

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Deploy
      run: |
       dotnet publish source -c release /p:PublishReadyToRun=true --self-contained
       dotnet publish source -c release -r linux-arm64 --self-contained
       cp "source/bin/release/net6.0/linux-x64/publish/source" assembler -f
       cp "source/bin/release/net6.0/linux-arm64/publish/source" assembler_arm -f
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: nightly-deploy-linux
       path: |
        assembler
        assembler_arm
        License.md
        README.md
        alphabets/
        assets/
        batchfiles/
        datasets/
        templates/
       retention-days: 21

  osx:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Deploy
      run: |
       dotnet publish source -c release /p:PublishReadyToRun=true --self-contained
       dotnet publish source -c release -r osx.11.0-arm64 --self-contained
       cp "source/bin/release/net6.0/osx-x64/publish/source" assembler
       cp "source/bin/release/net6.0/osx.11.0-arm64/publish/source" assembler_arm
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: nightly-deploy-osx
       path: |
        assembler
        assembler_arm
        License.md
        README.md
        alphabets/
        assets/
        batchfiles/
        datasets/
        templates/
       retention-days: 21         
