name: examples

on:
  push:
    branches:
      - 180

jobs:
  examples:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Run examples
      run: |
        dotnet run --project batchfiles/basic.txt
        dotnet run --project batchfiles/monoclonal.txt
        dotnet run --project batchfiles/polyclonal.txt
    - name: Copy Manual
      run: Copy-Item "BatchFiles.md" -Destination "results/BatchFiles.md" -Force
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        branch: gh-pages-examples
        folder: results