name: pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    uses: snijderlab/stitch/.github/workflows/check.yml@master
  
  benchmark:
    uses: snijderlab/stitch/.github/workflows/benchmark.yml@master  