name: pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    uses: snijderlab/stitch/.github/workflows/check.yml@master
  
  benchmark:
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'possible scoring change' }}
    uses: snijderlab/stitch/.github/workflows/benchmark.yml@master  