name: push

on:
  push:
    branches: [ master ]

jobs:
  check:
    uses: snijderlab/stitch/.github/workflows/check.yml@master

  deploy:
    uses: snijderlab/stitch/.github/workflows/deploy.yml@master