name: push

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  check:
    uses: snijderlab/stitch/.github/workflows/check.yml@master

  benchmark:
    uses: snijderlab/stitch/.github/workflows/benchmark.yml@master  
    secrets:
      BENCHMARK_ACTION_BOT_TOKEN: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}

  deploy:
    uses: snijderlab/stitch/.github/workflows/deploy.yml@master